---
#local_admin_user: administrator
#local_admin_pass: Ansiblem@nage
aad_admin_user: AzureAD\ttwinrm@trickyjoeintune.onmicrosoft.com
aad_admin_pass: Ansiblem@nage1111
appinstall_path: \\ttsmbstorage.file.core.windows.net\applications
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
#ansible_user: "{{ local_admin_user }}"
#ansible_password: "{{ local_admin_pass }}"
ansible_become_user: "{{ aad_admin_user }}"
ansible_become_password: "{{ aad_admin_pass }}"
