- hosts: azwin10
  gather_facts: false
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ adds_admin_user }}"
    ansible_become_password: "{{ adds_admin_pass }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    
  tasks:

  - name: Set an environment variable for app installation path
    win_environment:
      state: present
      name: appinstall
      value: "{{ appinstall_path }}"
      level: machine

  - name: join AD DS domain
    win_domain_membership:
      dns_domain_name: "{{ adds_fqdn }}"
      domain_admin_user: "{{ adds_admin_user }}"
      domain_admin_password: "{{ adds_admin_pass }}"
      domain_ou_path: "{{ adds_ou_path }}"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required

  - name: reboot pre-dependency installations
    win_reboot:
      
# Install runtimes and dependencies
    
  - name: Include runtime and dependencies playbook
    include: runtimes.yaml

  - name: Reboot post dependency installations
    win_reboot:

# OS Customisation


#  - name: reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hello
#      data: world
      
#  - name: dword reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hellod
#      data: 1
#      type: dword

#  - name: Run a multiple powershell commands
#    win_shell: |
#      New-Item -Path C:\temp -ItemType Directory
#      New-Item -Path C:\temp\ansible -ItemType Directory
#      write-host hello-mate >> c:\temp\ansible\test.txt

#  - name: Run a command under cmd
#    win_shell: echo ansible test >> C:\temp\test.txt && echo still here >> c:\temp\test.txt
#    args:
#      executable: cmd.exe


# Install service components

  - name: Install FSlogix apps
    win_shell: cmd /c "$env:appinstall\fslogix\Install-fslogixapps.cmd"
    args:
      creates: C:\Program Files\FSLogix\Apps\frxshell.exe

  - name: Install admin tools and image sealing script
    win_shell: cmd /c "$env:appinstall\masters admin tools\Install-masters.cmd"

# Install applications

- hosts: azwin10
  gather_facts: false
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ adds_admin_user }}"
    ansible_become_password: "{{ adds_admin_pass }}"
    ansible_become_flags: logon_type=interactive logon_flags=with_profile
    
  tasks:
  
  - name: Include applications playbook
    include: coreapplicationset.yaml