- hosts: azwin10
  gather_facts: false
  vars:
    ansible_become: no
    ansible_become_method: runas
    ansible_become_user: "{{ aad_admin_user }}"
    ansible_become_password: "{{ aad_admin_pass }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    
  tasks:

  - name: Run provisioning package to join to AAD
    win_shell: DISM.exe /Online /Add-ProvisioningPackage /PackagePath:C:\temp\w10AADjoin\w10AADjoin.ppkg

  - name: Disable RDP network level auth to allow AAD accounts to logon remotely.
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: SecurityLayer
      data: 0
      type: dword

  - name: Reboot post AD domain and intune linkup
    win_reboot:

  - name: Add AAD user as a local admin
    win_shell: net localgroup administrators "{{ aad_admin_user }}" /add

# OS Customisation

#  - name: reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hello
#      data: world
      
#  - name: dword reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hellod
#      data: 1
#      type: dword

#  - name: Run a multiple powershell commands
#    win_shell: |
#      New-Item -Path C:\temp -ItemType Directory
#      New-Item -Path C:\temp\ansible -ItemType Directory
#      write-host hello-mate >> c:\temp\ansible\test.txt

#  - name: Run a command under cmd
#    win_shell: echo ansible test >> C:\temp\test.txt && echo still here >> c:\temp\test.txt
#    args:
#      executable: cmd.exe

