- hosts: azwin10
  gather_facts: false
  vars:
    ansible_become: no
    ansible_become_method: runas
    ansible_become_user: "{{ aad_admin_user }}"
    ansible_become_password: "{{ aad_admin_pass }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    
  tasks:
  
  - name: download aad provisioning package
    ansible.windows.win_get_url:
      url: https://ttsmbstorage.blob.core.windows.net/aadjoin/AADjoin.zip
      dest: '%TEMP%\AADjoin.zip'
      
  - name: Unzip aad provisioning package
    win_unzip:
      src: '%TEMP%\AADjoin.zip'
      dest: '%TEMP%\AADjoin'
      creates: '%TEMP%\AADjoin'

  - name: Run AAD provisioning package to join to AAD
    win_shell: DISM.exe /Online /Add-ProvisioningPackage /PackagePath:"%TEMP%\AADjoin\w10AADjoin.ppkg"

  - name: Disable RDP network level auth to allow AAD accounts to logon remotely.
    win_shell: (Get-WmiObject -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -Filter "TerminalName='RDP-tcp'").SetUserAuthenticationRequired(0)

  - name: instal chocolately
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

  - name: install git
    win_shell: choco install git

  - name: Install-Module AzureAD
    win_shell: Install-Module AzureAD
    
  - name: download intune powershell from git
    win_shell: git clone https://github.com/microsoftgraph/powershell-intune-samples c:\psintune
    
#  - name: Reboot post AAD domain join
#    win_reboot:

#  - name: Add AAD user as a local admin
#    win_shell: net localgroup administrators "{{ aad_admin_user }}" /add

# OS Customisation

#  - name: reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hello
#      data: world
      
#  - name: dword reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hellod
#      data: 1
#      type: dword

#  - name: Run a multiple powershell commands
#    win_shell: |
#      New-Item -Path C:\temp -ItemType Directory
#      New-Item -Path C:\temp\ansible -ItemType Directory
#      write-host hello-mate >> c:\temp\ansible\test.txt

#  - name: Run a command under cmd
#    win_shell: echo ansible test >> C:\temp\test.txt && echo still here >> c:\temp\test.txt
#    args:
#      executable: cmd.exe

